import { ColorPalette } from "../theme/Palette.slint";
import { Spacing } from "../theme/Spacing.slint";
import { Typography } from "../theme/Typography.slint";

export component Separator inherits Rectangle {
	// Properties
	in property <string> text: "";
	in property <length> line-height: 1px;
	in property <color> text-color: ColorPalette.text-muted;
	in property <color> line-color: ColorPalette.border-light;
	
	height: 24px;
	background: transparent;
	
	HorizontalLayout {
		alignment: stretch;
		spacing: Spacing.component-gap-md;
		
		// Left line
		Rectangle {
			vertical-stretch: 0;
			y: (root.height - line-height) / 2;
			height: line-height;
			background: root.line-color;
		}
		
		// Text in the middle (optional)
		if text != "": Text {
			text: root.text;
			color: root.text-color;
			font-size: Typography.body-sm;
			vertical-alignment: center;
			horizontal-alignment: center;
		}
		
		// Right line
		if text != "": Rectangle {
			vertical-stretch: 0;
			y: (root.height - line-height) / 2;
			height: line-height;
			background: root.line-color;
		}
	}
}
