export global AssetTable {
	// Icon image assets (use directly in icon/image properties)
	out property <image> back-icon: @image-url("../assets/icons/back.svg");
	out property <image> google-icon: @image-url("../assets/icons/google.svg");
	out property <image> app-icon: @image-url("../assets/icons/icon.svg");
	out property <image> linkedin-icon: @image-url("../assets/icons/linkedin.svg");
	out property <image> lock-icon: @image-url("../assets/icons/lock.svg");
	out property <image> mail-icon: @image-url("../assets/icons/mail.svg");
	out property <image> planning-calculator-icon: @image-url("../assets/icons/planning-calculator.svg");
	out property <image> project-management-icon: @image-url("../assets/icons/project-management.svg");
	out property <image> team-icon: @image-url("../assets/icons/team.svg");
	out property <image> toggle-password-1-icon: @image-url("../assets/icons/toggle-password-1.svg");
	out property <image> toggle-password-2-icon: @image-url("../assets/icons/toggle-password-2.svg");
	out property <image> user-icon: @image-url("../assets/icons/user.svg");
	out property <image> menu-icon: @image-url("../assets/icons/menu.svg");
}
