import { VerticalBox, HorizontalBox } from "std-widgets.slint";
import {
	// Theme
	ColorPalette, 
	Spacing, 
	Typography,
	
	// Components
	Button,
	ButtonVariant,
	Input,
	Card,
	IconButton,
	Separator,
	VerificationCodeInput,
	Navbar,

	// Pages
	Counter,
	Settings,

	// Layouts
	HomeLayout

} from "@slint-ui/UI.slint";

import { AboutSlint } from "std-widgets.slint";


export component AppWindow inherits Window {
	title: "Slint on Android";
	default-font-family: Typography.font-family-base;
	background: ColorPalette.background;

	homeLayout := HomeLayout {
		if homeLayout.pageSelected == 1: Counter {
		
		}

		if homeLayout.pageSelected == 2: Settings {

		}
	}
}
