
import { Navbar } from "../components/Navbar.slint";
// import {  } from "std-widgets.slint";

import { Button, ButtonVariant } from "../components/Button.slint";
import { Spacing } from "../theme/Spacing.slint";
import { ColorPalette } from "../theme/Palette.slint";
import { AssetTable } from "../theme/AssetTable.slint";

import { PageNavigator, Pages } from "../PageNavigator.slint";

export component HomeLayout inherits Rectangle {
	// State for menu visibility
	property <bool> menu-open: false;
    
    // Layout
	VerticalLayout {
        spacing: 0px;

        Navbar {
            menu-clicked => {
                root.menu-open = !root.menu-open;
            }
        }

        @children
    }
	
	// Collapsible menu
	collapsibleMenu := Rectangle {
        height: root.menu-open ? (Spacing.button-height * 2 + 24px + 8px) : 0px;
        animate height { duration: 200ms; }
        background: ColorPalette.background-tertiary;
        clip: true;

        VerticalLayout {
            visible: root.menu-open;
            spacing: 8px;
            padding: 12px;

            Button {
                text: "Counter";
                height: Spacing.button-height;
                variant: PageNavigator.current-page == Pages.COUNTER ? ButtonVariant.primary : ButtonVariant.secondary;

                clicked => {
                    PageNavigator.navigate-to(Pages.COUNTER);
                    root.menu-open = false;
                }
            }

            Button {
                text: "Settings";
                height: Spacing.button-height;
                variant: PageNavigator.current-page == Pages.SETTINGS ? ButtonVariant.primary : ButtonVariant.secondary;

                clicked => {
                    PageNavigator.navigate-to(Pages.SETTINGS);
                    root.menu-open = false;
                }
            }
        }
    }
}
