
import { Navbar } from "../components/Navbar.slint";
// import {  } from "std-widgets.slint";

import { Button } from "../components/Button.slint";
import { Spacing } from "../theme/Spacing.slint";
import { ColorPalette } from "../theme/Palette.slint";
import { AssetTable } from "../theme/AssetTable.slint";

export component HomeLayout inherits Rectangle {
	// State for menu visibility
	property <bool> menu-open: false;
	out property <int> pageSelected: 1;

	callback menuOptionChanged(int);

	// Layout
	VerticalLayout {
		spacing: 0px;

		Navbar {
			menu-clicked => {
				root.menu-open = !root.menu-open;
			}
		}

		@children

	}
	
	// Collapsible menu
	collapsibleMenu := Rectangle {
		height: root.menu-open ? 3*60px : 0px;
		animate height { duration: 200ms; }
		background: #2228;
		clip: true;

		VerticalLayout {
			visible: root.menu-open;
			spacing: 8px;
			padding: 12px;

			Button {
				text: "Option 1";

				background: root.pageSelected == 1 ? #555 : transparent;
				clicked => {
					root.pageSelected = 1;
					root.menuOptionChanged(1);
				}
			}

			Button {
				text: "Option 2";

				background: root.pageSelected == 2 ? #555 : transparent;
				clicked => {
					root.pageSelected = 2;
					root.menuOptionChanged(2);
				}
			}

			Button {
				text: "Option 3";
				
				background: root.pageSelected == 3 ? #555 : transparent;
				clicked => {
					root.pageSelected = 3;
					root.menuOptionChanged(3);
				}
			}

		}
	}
}
