import { Button, ButtonVariant } from "../components/Button.slint";
import { ColorPalette, ThemeMode } from "../theme/Palette.slint";
import { Spacing } from "../theme/Spacing.slint";
import { Typography } from "../theme/Typography.slint";
import { Separator } from "../components/Separator.slint";

import { AboutSlint, HorizontalBox, VerticalBox } from "std-widgets.slint";

export component Settings inherits Rectangle {

	VerticalBox {
		spacing: Spacing.component-gap-md;
		padding: Spacing.component-gap-md;
		width: parent.width;
		height: parent.height;


		Text {
			text: "Theme";
			font-size: Typography.heading-lg;
			color: ColorPalette.text-primary;
			horizontal-alignment: center;
			height: Typography.heading-lg;
		}

		VerticalBox {
			spacing: Spacing.component-gap-md;

			Button {
				text: "Light Mode";
				height: Spacing.button-height;
				variant: ColorPalette.theme-mode == ThemeMode.LIGHT ?
						ButtonVariant.primary : ButtonVariant.secondary;
				

				clicked => {
					ColorPalette.theme-mode = ThemeMode.LIGHT;
				}
			}

			Button {
				text: "Dark Mode";
				height: Spacing.button-height;
				variant: ColorPalette.theme-mode == ThemeMode.DARK ?
						ButtonVariant.primary : ButtonVariant.secondary;

				clicked => {
					ColorPalette.theme-mode = ThemeMode.DARK;
				}
			}

			Button {
				text: "System";
				height: Spacing.button-height;
				variant: ColorPalette.theme-mode == ThemeMode.SYSTEM ?
						ButtonVariant.primary : ButtonVariant.secondary;

				clicked => {
					ColorPalette.theme-mode = ThemeMode.SYSTEM;
				}
			}
		}

		Separator {
			line-color: ColorPalette.brand-accent;
		}
		
	}
}