// Inter font is licensed under the SIL Open Font License (OFL)
// See: assets/fonts/OFL.txt for full license terms
import "./assets/fonts/Inter.ttf";

// Theme globals
import { ColorPalette } from "theme/Palette.slint";
import { Spacing } from "theme/Spacing.slint";
import { Typography } from "theme/Typography.slint";
import { AssetTable } from "theme/AssetTable.slint";

// Components
import { Button, ButtonVariant } from "components/Button.slint";
import { Input } from "components/Input.slint";
import { Card } from "components/Card.slint";
import { IconButton } from "components/IconButton.slint";
import { Separator } from "components/Separator.slint";
import { VerificationCodeInput } from "components/VerificationCodeInput.slint";
import { Navbar } from "components/Navbar.slint";

// Pages
import { Counter } from "pages/Counter.slint";
import { Settings } from "pages/Settings.slint";
import { TicTacToe } from "pages/TicTacToe.slint";

// Layouts
import { HomeLayout } from "layouts/HomeLayout.slint";


// Re-export everything
export { 
	// Theme
	ColorPalette,
	Spacing,
	Typography,
	AssetTable,
	
	// Components
	Button,
	ButtonVariant,
	Input,
	Card,
	IconButton,
	Separator,
	VerificationCodeInput,
	Navbar,

	// Pages
	Counter,
	Settings,
	TicTacToe,

	// Layouts
	HomeLayout,
}
